<?php
/** Generate the native core schema artifact from wp_get_db_schema(). */

if ( ! defined( 'ABSPATH' ) ) {
	throw new RuntimeException( 'Run this generator through WP-CLI.' );
}
if ( ! function_exists( 'wp_get_db_schema' ) ) {
	require_once ABSPATH . 'wp-admin/includes/schema.php';
}
require_once dirname( __DIR__ ) . '/inc/class-wp-markdown-native-core-schema-catalog.php';

global $wpdb, $wp_version;
$prefixes = array( (string) $wpdb->prefix, (string) $wpdb->base_prefix );
if ( is_multisite() || defined( 'WP_INSTALLING_NETWORK' ) ) {
	throw new RuntimeException( 'Generate the catalog from a single-site runtime where WP_INSTALLING_NETWORK is undefined.' );
}
$single = WP_Markdown_Native_Core_Schema_Catalog::compile( wp_get_db_schema( 'all' ), $prefixes );
define( 'WP_INSTALLING_NETWORK', true );
foreach ( $wpdb->ms_global_tables as $table ) {
	$wpdb->{$table} = $wpdb->base_prefix . $table;
}
$multisite = WP_Markdown_Native_Core_Schema_Catalog::compile( wp_get_db_schema( 'all' ), $prefixes );

$output = getenv( 'MDI_NATIVE_SCHEMA_OUTPUT' );
if ( ! is_string( $output ) || '' === $output ) {
	throw new RuntimeException( 'MDI_NATIVE_SCHEMA_OUTPUT is required.' );
}
$artifact = array(
	'schema'            => 'mdi-native-core-schema/v1',
	'wordpress_version' => (string) $wp_version,
	'single_site'       => $single,
	'multisite'         => $multisite,
	'hashes'            => array(
		'single_site' => WP_Markdown_Native_Core_Schema_Catalog::hash( $single ),
		'multisite'   => WP_Markdown_Native_Core_Schema_Catalog::hash( $multisite ),
	),
);
$export = str_replace( "=> \n", "=>\n", var_export( $artifact, true ) );
$contents = "<?php\n/** Generated by tools/generate-native-core-schema.php; do not edit manually. */\nreturn "
	. $export . ";\n";
$temporary = $output . '.tmp-' . getmypid();
if ( false === file_put_contents( $temporary, $contents ) || ! rename( $temporary, $output ) ) {
	@unlink( $temporary );
	throw new RuntimeException( 'Failed to write the generated native core schema catalog.' );
}
